---
- hosts: all
  tasks:
  - name: check JAVA folder exist on server
    shell: find / -iname "*java*" -print
    become: yes
    ignore_errors: yes
    register: output
    
  - name: Debug the output
    debug:
     msg:"hi - {{ output }}"
